version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: academy_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0303456"
      MYSQL_DATABASE: academy_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: academy_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "0303456"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data: